# Generated by Django 3.1.4 on 2021-04-18 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20210220_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='detail',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
